MVCSkeleton.Web/Controllers/ChartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace MVCSkeleton.Web.Controllers
{
    [Authorize(Roles = "User,Admin")]
    public class ChartController : Controller
    {

        public ActionResult Charts()
        {
            return View();
        }

        public ActionResult Float()
        {
            return View();
        }

        public ActionResult BarChart()
        {
            var chart = new Chart(width: 300, height: 200)
              .AddSeries(
                          chartType: "column",
                          xValue: new[] { "10 Records", "20 Records", "30 Records", "40 Records" },
                          yValues: new[] { "50", "60", "78", "80" })
                          .GetBytes("png");
            return File(chart, "image/bytes");
        }

        public ActionResult PieChart()
        {
            var chart = new Chart(width: 300, height: 200)
              .AddSeries(
                          chartType: "pie",
                          xValue: new[] { "10 Records", "20 Records", "30 Records", "40 Records" },
                          yValues: new[] { "50", "60", "78", "80" })
                          .GetBytes("png");
            return File(chart, "image/bytes");
        }

        public ActionResult StackedBarChart()
        {
            var chart = new Chart(width: 300, height: 200)
              .AddSeries(
                          chartType: "bar",
                          xValue: new[] { "10 Records", "20 Records", "30 Records", "40 Records" },
                          yValues: new[] { "50", "60", "78", "80" })
                          .GetBytes("png");
            return File(chart, "image/bytes");
        }

        public ActionResult LineChart()
        {
            var chart = new Chart(width: 300, height: 200)
              .AddSeries(
                          chartType: "line",
                          xValue: new[] { "10 Records", "20 Records", "30 Records", "40 Records" },
                          yValues: new[] { "50", "60", "78", "80" })
                          .GetBytes("png");
            return File(chart, "image/bytes");
        }

        public ActionResult Radial()
        {
            return View();
        }

    }
}

MVCSkeleton.Web/Controllers/ExtraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCSkeleton.Web.Controllers
{
    [Authorize(Roles = "User,Admin")]
    public class ExtraController : Controller
    {
        public ActionResult Calender()
        {
            return View();
        }

        public ActionResult Timeline()
        {
            return View();
        }

        public ActionResult Search()
        {
            return View();
        }

        public ActionResult Invoice()
        {
            return View();
        }

        public ActionResult Mailbox()
        {
            return View();
        }

        public ActionResult Filebox()
        {
            return View();
        }
    }
}

MVCSkeleton.Web/Controllers/FormController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCSkeleton.Web.Controllers
{
    [Authorize(Roles = "User,Admin")]
    public class FormController : Controller
    {
        public ActionResult Standard()
        {
            return View();
        }

        public ActionResult Wizard()
        {
            return View();
        }

        public ActionResult Validation()
        {
            return View();
        }

        public ActionResult Extended()
        {
            return View();
        }
    }
}

MVCSkeleton.Web/Controllers/MapController.cs
using System.Web.Mvc;

namespace MVCSkeleton.Web.Controllers
{
    [Authorize(Roles = "User,Admin")]
    public class MapController : Controller
    {
        public ActionResult Google()
        {
            return View();
        }

        public ActionResult Vector()
        {
            return View();
        }
    }
}

MVCSkeleton.Web/Views/Shared/NotApprovalUser.cshtml
<h2>Non-approved</h2>

<p>Your account has not been approved yet</p>

MVCSkeleton.Web/Views/Shared/_Aside.cshtml
 <!-- START aside-->
<aside class="offsidebar">
    <!-- START Off Sidebar (right)-->
    <nav>
        <ul class="nav">
            <!-- START user info-->
            <li>
                <div class="item">
                    <div class="p-lg">
                        <div class="text-center">
                            <p>
                                <img src="/assets/app/img/user/02.jpg" alt="Image" class="img-circle img-thumbnail thumb64">
                            </p>
                            <p>
                                <strong>Arnold</strong>
                            </p>
                        </div>
                    </div>
                </div>
            </li>
            <!-- END user info-->
            <li class="p">
                <div class="form-group has-feedback">
                    <input type="text" placeholder="Search contacts.." class="form-control">
                    <em class="fa fa-search form-control-feedback text-muted"></em>
                </div>
            </li>
            <!-- START list title-->
            <li class="p">
                <small class="text-muted">ONLINE</small>
            </li>
            <!-- END list title-->
            <li>
                <!-- START User status-->
                <a href="#" class="media p mt0">
                    <span class="pull-right">
                        <span class="point point-success point-lg"></span>
                    </span>
                    <span class="pull-left">
                        <!-- Contact avatar-->
                        <img src="/assets/app/img/user/05.jpg" alt="Image" class="media-object img-circle thumb48">
                    </span>
                    <!-- Contact info-->
                    <span class="media-body">
                        <span class="media-heading">
                            <strong>Laura Sam</strong>
                            <br>
                            <small class="text-muted">lau39</small>
                        </span>
                    </span>
                </a>
                <!-- END User status-->
                <!-- START User status-->
                <a href="#" class="media p mt0">
                    <span class="pull-right">
                        <span class="point point-success point-lg"></span>
                    </span>
                    <span class="pull-left">
                        <!-- Contact avatar-->
                        <img src="/assets/app/img/user/06.jpg" alt="Image" class="media-object img-circle thumb48">
                    </span>
                    <!-- Contact info-->
                    <span class="media-body">
                        <span class="media-heading">
                            <strong>Beverley Pierce</strong>
                            <br>
                            <small class="text-muted">be40210</small>
                        </span>
                    </span>
                </a>
                <!-- END User status-->
                <!-- START User status-->
                <a href="#" class="media p mt0">
                    <span class="pull-right">
                        <span class="point point-danger point-lg"></span>
                    </span>
                    <span class="pull-left">
                        <!-- Contact avatar-->
                        <img src="/assets/app/img/user/07.jpg" alt="Image" class="media-object img-circle thumb48">
                    </span>
                    <!-- Contact info-->
                    <span class="media-body">
                        <span class="media-heading">
                            <strong>Mika Long</strong>
                            <br>
                            <small class="text-muted">longlong</small>
                        </span>
                    </span>
                </a>
                <!-- END User status-->
                <!-- START User status-->
                <a href="#" class="media p mt0">
                    <span class="pull-right">
                        <span class="point point-warning point-lg"></span>
                    </span>
                    <span class="pull-left">
                        <!-- Contact avatar-->
                        <img src="/assets/app/img/user/08.jpg" alt="Image" class="media-object img-circle thumb48">
                    </span>
                    <!-- Contact info-->
                    <span class="media-body">
                        <span class="media-heading">
                            <strong>Danielle Berry</strong>
                            <br>
                            <small class="text-muted">hunter49</small>
                        </span>
                    </span>
                </a>
                <!-- END User status-->
            </li>
            <!-- START list title-->
            <li class="p">
                <small class="text-muted">OFFLINE</small>
            </li>
            <!-- END list title-->
            <li>
                <!-- START User status-->
                <a href="#" class="media p mt0">
                    <span class="pull-right">
                        <span class="point point-lg"></span>
                    </span>
                    <span class="pull-left">
                        <!-- Contact avatar-->
                        <img src="/assets/app/img/user/09.jpg" alt="Image" class="media-object img-circle thumb48">
                    </span>
                    <!-- Contact info-->
                    <span class="media-body">
                        <span class="media-heading">
                            <strong>Martin Cooper</strong>
                            <br>
                            <small class="text-muted">maryo</small>
                        </span>
                    </span>
                </a>
                <!-- END User status-->
                <!-- START User status-->
                <a href="#" class="media p mt0">
                    <span class="pull-right">
                        <span class="point point-lg"></span>
                    </span>
                    <span class="pull-left">
                        <!-- Contact avatar-->
                        <img src="/assets/app/img/user/10.jpg" alt="Image" class="media-object img-circle thumb48">
                    </span>
                    <!-- Contact info-->
                    <span class="media-body">
                        <span class="media-heading">
                            <strong>Daniel Curtis</strong>
                            <br>
                            <small class="text-muted">danni</small>
                        </span>
                    </span>
                </a>
                <!-- END User status-->
            </li>
            <li>
                <!-- Optional link to list more users-->
                <a href="#" title="See more contacts" class="p">
                    <strong>
                        <small class="text-muted">&hellip;</small>
                    </strong>
                </a>
            </li>
        </ul>
    </nav>
    <!-- END Off Sidebar (right)-->
</aside>
<!-- END aside-->

MVCSkeleton.Web/Views/Shared/_Navigation.cshtml
<!-- START aside-->
<aside class="aside">
    <!-- START Sidebar (left)-->
    <nav class="sidebar">
        <ul class="nav">
            <!-- START Menu-->
            <li class="nav-heading">Main</li>
            <li>
                <a href="" title="Dashboard" data-toggle="collapse-next" class="has-submenu">
                    <em class="fa fa-dot-circle-o"></em>
                    <div class="label label-primary pull-right">10</div>
                    <span class="item-text">Dashboard</span>
                </a>
                <!-- START SubMenu item-->
                <ul class="nav collapse">
                    <li>
                        <a href="@Url.Action("Dashboard","Home")" title="Default" data-toggle="" class="no-submenu">
                            <span class="item-text">Default</span>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Dashboard2","Home")" title="Two Sidebar" data-toggle="" class="no-submenu">
                            <span class="item-text">Two Sidebar</span>
                        </a>
                    </li>
                </ul>
                <!-- END SubMenu item-->
            </li>
            <li>
                <a href="#" title="Pages" data-toggle="collapse-next" class="has-submenu">
                    <em class="fa fa-file-text-o"></em>
                    <span class="item-text">Pages</span>
                </a>
                <!-- START SubMenu item-->
                <ul class="nav collapse ">
                    <li>
                        <a href="@Url.Action("Landing","Home")" title="Landing" data-toggle="" class="no-submenu">
                            <span class="item-text">Landing</span>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Login","Home")" title="Login" data-toggle="" class="no-submenu">
                            <span class="item-text">Login</span>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("LoginMulti","Home")" title="Login Multi" data-toggle="" class="no-submenu">
                            <span class="item-text">Login Multi</span>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("SignUp","Home")" title="Sign up" data-toggle="" class="no-submenu">
                            <span class="item-text">Sign up</span>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Lock","Home")" title="Lock" data-toggle="" class="no-submenu">
                            <span class="item-text">Lock</span>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("RecoveryPassword","Home")" title="Recover Password" data-toggle="" class="no-submenu">
                            <span class="item-text">Recover Password</span>
                        </a>
                    </li>
                </ul>
                <!-- END SubMenu item-->
            </li>
            <li class="nav-heading">More</li>
            <li>
                <a href="#" title="Maps" data-toggle="collapse-next" class="has-submenu">
                    <em class="fa fa-globe"></em>
                    <div class="label label-primary pull-right">new</div>
                    <span class="item-text">Maps</span>
                </a>
                <!-- START SubMenu item-->
                <ul class="nav collapse ">
                    <li>
                        <a href="@Url.Action("Google","Map")" title="Google Maps" data-toggle="" class="no-submenu">
                            <span class="item-text">Google Maps</span>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Vector","Map")" title="Vector Maps" data-toggle="" class="no-submenu">
                            <div class="label label-primary pull-right">new</div>
                            <span class="item-text">Vector Maps</span>
                        </a>
                    </li>
                </ul>
                <!-- END SubMenu item-->
            </li>
            <li>
                <a href="#" title="Charts" data-toggle="collapse-next" class="has-submenu">
                    <em class="fa fa-area-chart"></em>
                    <div class="label label-primary pull-right">new</div>
                    <span class="item-text">Charts</span>
                </a>
                <!-- START SubMenu item-->
                <ul class="nav collapse ">
                    <li>
                        <a href="@Url.Action("Charts","Chart")" title="Flot" data-toggle="" class="no-submenu">
                            <span class="item-text">Charts</span>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Radial","Chart")" title="Radial" data-toggle="" class="no-submenu">
                            <div class="label label-primary pull-right">new</div>
                            <span class="item-text">Radial</span>
                        </a>
                    </li>
                </ul>
                <!-- END SubMenu item-->
            </li>
            <li>
                <a href="#" title="Tables" data-toggle="collapse-next" class="has-submenu">
                    <em class="fa fa-table"></em>
                    <span class="item-text">Tables</span>
                </a>
                <!-- START SubMenu item-->
                <ul class="nav collapse ">
                    <li>
                        <a href="@Url.Action("DataTable","Table")" title="Data Table" data-toggle="" class="no-submenu">
                            <span class="item-text">Data Table</span>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Standard","Table")" title="Standard" data-toggle="" class="no-submenu">
                            <span class="item-text">Standard</span>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Extended","Table")" title="Extended" data-toggle="" class="no-submenu">
                            <span class="item-text">Extended</span>
                        </a>
                    </li>
                </ul>
                <!-- END SubMenu item-->
            </li>
            <li>
                <a href="#" title="Forms" data-toggle="collapse-next" class="has-submenu">
                    <em class="fa fa-edit"></em>
                    <span class="item-text">Forms</span>
                </a>
                <!-- START SubMenu item-->
                <ul class="nav collapse ">
                    <li>
                        <a href="@Url.Action("Standard","Form")" title="Standard" data-toggle="" class="no-submenu">
                            <span class="item-text">Standard</span>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Wizard","Form")" title="Wizard" data-toggle="" class="no-submenu">
                            <span class="item-text">Wizard</span>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Validation","Form")" title="Validation" data-toggle="" class="no-submenu">
                            <span class="item-text">Validation</span>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Extended","Form")" title="Extended" data-toggle="" class="no-submenu">
                            <span class="item-text">Extended</span>
                        </a>
                    </li>
                </ul>
                <!-- END SubMenu item-->
            </li>
            <li>
                <a href="#" title="Extras" data-toggle="collapse-next" class="has-submenu">
                    <em class="fa fa-plus"></em>
                    <div class="label label-primary pull-right">new</div>
                    <span class="item-text">Extras</span>
                </a>
                <!-- START SubMenu item-->
                <ul class="nav collapse ">
                    <li>
                        <a href="@Url.Action("Calender","Extra")" title="Calendar" data-toggle="" class="no-submenu">
                            <span class="item-text">Calendar</span>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Timeline","Extra")" title="Timeline" data-toggle="" class="no-submenu">
                            <span class="item-text">Timeline</span>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Search","Extra")" title="Search" data-toggle="" class="no-submenu">
                            <span class="item-text">Search</span>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Invoice","Extra")" title="Invoice" data-toggle="" class="no-submenu">
                            <span class="item-text">Invoice</span>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Mailbox","Extra")" title="Mailbox" data-toggle="" class="no-submenu">
                            <span class="item-text">Mailbox</span>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Filebox","Extra")" title="Filebox" data-toggle="" class="no-submenu">
                            <div class="label label-primary pull-right">new</div>
                            <span class="item-text">Filebox</span>
                        </a>
                    </li>
                </ul>
                <!-- END SubMenu item-->
            </li>
        </ul>
    </nav>
    <!-- END Sidebar (left)-->
</aside>
<!-- End aside-->

MVCSkeleton.Web/Views/Shared/_PageLayout.cshtml
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="ie ie6 lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="ie ie7 lt-ie9 lt-ie8"        lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="ie ie8 lt-ie9"               lang="en"> <![endif]-->
<!--[if IE 9]>    <html class="ie ie9"                      lang="en"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en" class="no-ie">
<!--<![endif]-->
<head>
    <!-- Meta-->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="">
    <title>Wintermin - Bootstrap Admin Theme</title>
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]><script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script><script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script><![endif]-->
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/commoncss")
</head>
<body>

    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/pagescripts")
</body>
</html>

MVCSkeleton.Web/Views/Shared/_SlideBar.cshtml
<!-- START Off Sidebar (right)-->
<nav>
    <ul class="nav">
        <!-- START user info-->
        <li>
            <div class="item">
                <div class="p-lg">
                    <div class="text-center">
                        <p>
                            <img src="../../assets/app/img/user/02.jpg" alt="Image" class="img-circle img-thumbnail thumb64">
                        </p>
                        <p>
                            <strong>Arnold</strong>
                        </p>
                    </div>
                </div>
            </div>
        </li>
        <!-- END user info-->
        <li class="p">
            <div class="form-group has-feedback">
                <input type="text" placeholder="Search contacts.." class="form-control">
                <em class="fa fa-search form-control-feedback text-muted"></em>
            </div>
        </li>
        <!-- START list title-->
        <li class="p">
            <small class="text-muted">ONLINE</small>
        </li>
        <!-- END list title-->
        <li>
            <!-- START User status-->
            <a href="#" class="media p mt0">
                <span class="pull-right">
                    <span class="point point-success point-lg"></span>
                </span>
                <span class="pull-left">
                    <!-- Contact avatar-->
                    <img src="../../assets/app/img/user/05.jpg" alt="Image" class="media-object img-circle thumb48">
                </span>
                <!-- Contact info-->
                <span class="media-body">
                    <span class="media-heading">
                        <strong>Laura Sam</strong>
                        <br>
                        <small class="text-muted">lau39</small>
                    </span>
                </span>
            </a>
            <!-- END User status-->
            <!-- START User status-->
            <a href="#" class="media p mt0">
                <span class="pull-right">
                    <span class="point point-success point-lg"></span>
                </span>
                <span class="pull-left">
                    <!-- Contact avatar-->
                    <img src="../../assets/app/img/user/06.jpg" alt="Image" class="media-object img-circle thumb48">
                </span>
                <!-- Contact info-->
                <span class="media-body">
                    <span class="media-heading">
                        <strong>Beverley Pierce</strong>
                        <br>
                        <small class="text-muted">be40210</small>
                    </span>
                </span>
            </a>
            <!-- END User status-->
            <!-- START User status-->
            <a href="#" class="media p mt0">
                <span class="pull-right">
                    <span class="point point-danger point-lg"></span>
                </span>
                <span class="pull-left">
                    <!-- Contact avatar-->
                    <img src="../../assets/app/img/user/07.jpg" alt="Image" class="media-object img-circle thumb48">
                </span>
                <!-- Contact info-->
                <span class="media-body">
                    <span class="media-heading">
                        <strong>Mika Long</strong>
                        <br>
                        <small class="text-muted">longlong</small>
                    </span>
                </span>
            </a>
            <!-- END User status-->
            <!-- START User status-->
            <a href="#" class="media p mt0">
                <span class="pull-right">
                    <span class="point point-warning point-lg"></span>
                </span>
                <span class="pull-left">
                    <!-- Contact avatar-->
                    <img src="../../assets/app/img/user/08.jpg" alt="Image" class="media-object img-circle thumb48">
                </span>
                <!-- Contact info-->
                <span class="media-body">
                    <span class="media-heading">
                        <strong>Danielle Berry</strong>
                        <br>
                        <small class="text-muted">hunter49</small>
                    </span>
                </span>
            </a>
            <!-- END User status-->
        </li>
        <!-- START list title-->
        <li class="p">
            <small class="text-muted">OFFLINE</small>
        </li>
        <!-- END list title-->
        <li>
            <!-- START User status-->
            <a href="#" class="media p mt0">
                <span class="pull-right">
                    <span class="point point-lg"></span>
                </span>
                <span class="pull-left">
                    <!-- Contact avatar-->
                    <img src="../../assets/app/img/user/09.jpg" alt="Image" class="media-object img-circle thumb48">
                </span>
                <!-- Contact info-->
                <span class="media-body">
                    <span class="media-heading">
                        <strong>Martin Cooper</strong>
                        <br>
                        <small class="text-muted">maryo</small>
                    </span>
                </span>
            </a>
            <!-- END User status-->
            <!-- START User status-->
            <a href="#" class="media p mt0">
                <span class="pull-right">
                    <span class="point point-lg"></span>
                </span>
                <span class="pull-left">
                    <!-- Contact avatar-->
                    <img src="../../assets/app/img/user/10.jpg" alt="Image" class="media-object img-circle thumb48">
                </span>
                <!-- Contact info-->
                <span class="media-body">
                    <span class="media-heading">
                        <strong>Daniel Curtis</strong>
                        <br>
                        <small class="text-muted">danni</small>
                    </span>
                </span>
            </a>
            <!-- END User status-->
        </li>
        <li>
            <!-- Optional link to list more users-->
            <a href="#" title="See more contacts" class="p">
                <strong>
                    <small class="text-muted">&hellip;</small>
                </strong>
            </a>
        </li>
    </ul>
</nav>
<!-- END Off Sidebar (right)-->